name: .NET

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Build & Test
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./codeclimate-test-reporter
        chmod +x ./codeclimate-test-reporter
        
        dotnet tool install --global cake.tool
        
        ./codeclimate-test-reporter before-build
        
        dotnet-cake --target=Coverage

        ./codeclimate-test-reporter after-build -t lcov -r ea524caacce9f6a2a0469a9b60ff88136b57dadedf5a758e643c95533c5716eb -p ./ --exit-code $?
